{"name": "test_5[6*9-42]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 54 == 42\n +  where 54 = eval('6*9')", "trace": "test_input = '6*9', expected = 42\n\n    @pytest.mark.parametrize(\"test_input,expected\", [(\"3+5\", 8), (\"2+4\", 6), (\"6*9\", 42)])\n    def test_5(test_input, expected):\n>       assert eval(test_input) == expected\nE       AssertionError: assert 54 == 42\nE        +  where 54 = eval('6*9')\n\ntestcases/auto_test.py:34: AssertionError"}, "parameters": [{"name": "test_input", "value": "'6*9'"}, {"name": "expected", "value": "42"}], "start": 1595575310367, "stop": 1595575310367, "uuid": "18ff1d42-f7dc-476e-8c83-df265937e32b", "historyId": "ba21424426d25b4c36c8a7794ccd87ae", "testCaseId": "3cfff9bc708ac777a55cd999223fbaf2", "fullName": "testcases.auto_test#test_5", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "auto_test"}, {"name": "host", "value": "duan-XPS-15-9570"}, {"name": "thread", "value": "10814-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.auto_test"}]}